version: '3.9'

services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment: 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports: 
      - 9092:9092
    networks: 
      - microservice
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment: 
      ZOOKEEPER_CLIENT_PORT: 2181
    networks: 
      - microservice

networks:
  microservice: